name: nila # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Lidar based ros humanoid robot # 79 char long summary
description: |
  you can run instal nila in your ubuntu 20.0.4 with just one line

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
 ros-tutorials:
   plugin: catkin
   source: https://github.com/athulkrishnaaei/nila_bot
   source-branch: develop
   source-subdir: ros2_ws
   stage-packages:
       - ros-foxy-roslaunch
 
apps:
 ros-talker-listener:
   command: opt/ros/foxy/bin/setup.bash launch_robot.launch.py
   extensions: [ros2-foxy]